### ISSUE TITLE
Modbus lvlibp avoids upgrading the custom device to LV 2015 and upper

### ISSUE THREAD

**Issue by ghost** [NIVeriStandAdd-Ons/Modbus-Custom-Device-v2#35]
LabVIEW 2015 and upper refuses to load Modbus lvlibp because it has been compiled for LV2014 only.
Please provide version sof the lvlibp for LV2015 and upper.

**Comment by tannerblair** [comment]
You can find the source for the PPL at the following location:
https://github.com/NIVeriStandAdd-Ons/Modbus-Custom-Device-PPL

You can then build PPLs for each target type you want to support in the LV version you're using. We can't reasonably ship versions of the PPL each target type and version of LabVIEW.
